language: cpp
compiler: gcc
sudo: require
dist: trusty

before_install:
    - sudo add-apt-repository ppa:beineri/opt-qt58-trusty -y
    - sudo apt-get update -qq
    
install: 
    - sudo apt-get -y install libpulse0 qt58base qt58x11extras qt58tools liblastfm-dev libtag1-dev gettext libboost-dev libboost-serialization-dev cmake libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libglew1.5-dev libqjson-dev libgpod-dev libplist-dev libusbmuxd-dev libmtp-dev libcdio-dev protobuf-compiler libprotobuf-dev libcrypto++-dev libfftw3-dev libsparsehash-dev libpulse-dev libqtwebkit-dev libechonest-dev libchromaprint-dev libqca2-dev
    - source /opt/qt58/bin/qt58-env.sh
    - # Build sqlite with -DSQLITE_ENABLE_FTS3_TOKENIZER
    - # https://github.com/clementine-player/Clementine/issues/5484#issuecomment-282595800
    - wget https://sqlite.org/2017/sqlite-autoconf-3160200.tar.gz
    - tar xf sqlite-autoconf-*.tar.gz
    - cd sqlite*
    - ./configure --prefix=/usr --disable-static CFLAGS="-g -O2 -DSQLITE_ENABLE_FTS3_TOKENIZER=1 -DSQLITE_ENABLE_FTS3=1 -DSQLITE_ENABLE_COLUMN_METADATA=1 -DSQLITE_ENABLE_UNLOCK_NOTIFY=1 -DSQLITE_SECURE_DELETE=1 -DSQLITE_ENABLE_DBSTAT_VTAB=1" && make && sudo make install
    - make
    - sudo make install
    - cd -

script:
  - cd bin/
  - cmake -DCMAKE_INSTALL_PREFIX=/usr ../
  - make -j4
  - make INSTALL_ROOT=appdir install ; find .
  - wget -c "https://github.com/probonopd/linuxdeployqt/releases/download/continuous/linuxdeployqt-continuous-x86_64.AppImage" 
  - chmod a+x linuxdeployqt*.AppImage
  - unset QTDIR; unset QT_PLUGIN_PATH ; unset LD_LIBRARY_PATH
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/clementine.desktop -bundle-non-qt-libs
  - ./linuxdeployqt*.AppImage ./appdir/usr/share/applications/clementine.desktop -appimage 
  - curl --upload-file ./Clementine*.AppImage https://transfer.sh/Clementine-git.$(git rev-parse --short HEAD)-x86_64.AppImage 
